---
name: 'Install PHP'
description: 'Install PHP'
inputs:
  directory:
    description: 'Directory to run composer install'
    required: false
    default: '.'
  php-version:
    description: 'PHP version'
    required: false
    default: '8.4'
  php-coverage:
    description: 'PHP coverage (xdebug|none)'
    required: false
    default: 'none'
  composer-flags:
    description: 'Flags to add to "composer install"'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        extensions: bcmath, curl, dom, gd, libxml, mbstring, pcntl, redis, zip
        coverage: ${{ inputs.php-coverage }}

    - name: Get Composer Cache Directory
      shell: bash
      id: composer-cache
      run: echo "dir=$(cd ${{ inputs.directory }} && composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('${{ inputs.directory }}/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      shell: bash
      run: cd ${{ inputs.directory }} && composer install --prefer-dist --no-interaction --optimize-autoloader ${{ inputs.composer-flags }}
